/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prisonmanagementsystem;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author al-sany
 */
public class manageOptionOfGuard extends javax.swing.JFrame {

    /**
     * Creates new form manageOptionOfGuard
     */
    String id;
    DBConnect dbc=new DBConnect();
    
    public manageOptionOfGuard() {
        initComponents();
    }
    
    public manageOptionOfGuard(String id,String Name){
        initComponents();
        this.id=id;
        jLabel2.setText(id);
        jLabel4.setText(Name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("San Francisco Display", 1, 24)); // NOI18N
        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("San Francisco Display", 0, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("San Francisco Display", 1, 24)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("San Francisco Display", 0, 24)); // NOI18N
        jLabel4.setText("jLabel4");

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("San Francisco Display", 0, 24)); // NOI18N
        jButton1.setText("CHANGE ZONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("San Francisco Display", 0, 24)); // NOI18N
        jButton4.setText("SWAP ZONE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton1)
                        .addGap(229, 229, 229)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addGap(96, 96, 96))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("oooooooooooooooooo"+id);
        changeGuardZone ccg=new changeGuardZone(id);
        ccg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String gid;
        int m=0,n=0,o=0,x=0,y=0,z=0;
        gid=JOptionPane.showInputDialog("Input other guards id:", "");
        try{
            int Gid=Integer.parseInt(gid);
            ResultSet res=dbc.getResultSet("select * from hr.employee where designation='Guard' and id="+gid);
            try {
                if(res.next()){
                    String query="select distinct(row_no),floor,building_no from hr.cell c,hr.cellguard g where c.cellno=g.cell and g.guard="+gid;
                    ResultSet res1=dbc.getResultSet(query);
                    while(res1.next()){
                        x=Integer.parseInt(res1.getString("row_no"));
                        y=Integer.parseInt(res1.getString("floor"));
                        z=Integer.parseInt(res1.getString("building_no"));
                    }
                    query="select distinct(row_no),floor,building_no from hr.cell c,hr.cellguard g where c.cellno=g.cell and g.guard="+id;
                    ResultSet res2=dbc.getResultSet(query);
                    while(res2.next()){
                        m=Integer.parseInt(res2.getString("row_no"));
                        n=Integer.parseInt(res2.getString("floor"));
                        o=Integer.parseInt(res2.getString("building_no"));
                    }
                   // ResultSet res1=dbc.getResultSet("select row_no,floor,building_no from hr.cell,hr.cellguard where cellno=")
                    CallableStatement cst=dbc.connection().prepareCall("{CALL hr.cell_guard_packg.changeZone(?,?,?,?,?,?,?)}");
                    cst.setInt(1, Integer.parseInt(id));
                    cst.setInt(2, z);
                    cst.setInt(3, y);
                    cst.setInt(4, x);
                    cst.setInt(5, o);
                    cst.setInt(6, n);
                    cst.setInt(7, m);
                    Connection cn=dbc.connection();
                    cn.setAutoCommit(false);
                    Statement stmt=dbc.connection().createStatement();
                    stmt.addBatch("lock table hr.cellguard in exclusive mode nowait");
                    stmt.executeBatch();
                    cst.execute();
                    CallableStatement cst1=dbc.connection().prepareCall("{CALL hr.cell_guard_packg.changeZone(?,?,?,?,?,?,?)}");
                    cst1.setInt(1, Gid);
                    cst1.setInt(2, o);
                    cst1.setInt(3, n);
                    cst1.setInt(4, m);
                    cst1.setInt(5, z);
                    cst1.setInt(6, y);
                    cst1.setInt(7, x);
                    cst1.execute();
                    cn.commit(); 
                    JOptionPane.showMessageDialog(rootPane, "Zone have been swapped successfully.");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Other Guard id is not valid.");
                }    
            } catch (SQLException ex) {
                Logger.getLogger(manageOptionOfGuard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, "Other Guard id is not valid.");
        }    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageOptionOfGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageOptionOfGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageOptionOfGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageOptionOfGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageOptionOfGuard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
