/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prisonmanagementsystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author al-sany
 */
public class superAdmin extends javax.swing.JFrame {

    /**
     * Creates new form superAdmin
     */
    DBConnect dbc=new DBConnect();
    ResultSet res;
    
    public superAdmin() {
        initComponents();
    }
    
   /* DefaultTableModel tableModel = new DefaultTableModel() {

    @Override
        public boolean isCellEditable(int row, int column) {
        //all cells false
            return false;
        }
    };
*/
    //jTable1.setModel(tableModel)
    
    public void populateOnJTable(String query, String col[]){
        try {
            // TODO add your handling code here:
      
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            tableModel.setRowCount(0); //start inserting from first row
            tableModel.setColumnCount(col.length); //set column number
            
            //setting column headers
            for(int i=0;i<col.length;i++){
                jTable1.getColumnModel().getColumn(i).setHeaderValue(col[i]);
            }
            jTable1.getTableHeader().repaint();
            

            //tableModel.setDefaultEditor(Object.class, null);


            res=dbc.getResultSet(query);
            while(res.next()){
                //tableModel.setRowCount(0);
                Object [] rowData = new Object[col.length];               
                for (int i = 0; i < rowData.length; ++i){
                    rowData[i] = res.getObject(i+1);
                }
                tableModel.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(superAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("San Francisco Display", 1, 20)); // NOI18N
        jButton1.setText("Prisoners Table logs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton2.setFont(new java.awt.Font("San Francisco Display", 1, 20)); // NOI18N
    jButton2.setText("Archived Prisnoers");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jButton3.setFont(new java.awt.Font("San Francisco Display", 1, 18)); // NOI18N
    jButton3.setText("DEFECTED CELL");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(32, 32, 32))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton3)
                    .addGap(53, 53, 53)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(39, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(jButton1)
                    .addGap(34, 34, 34)
                    .addComponent(jButton2)
                    .addGap(36, 36, 36)
                    .addComponent(jButton3))
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(59, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String query="select * from hr.prisonerslogs";
        String col[]=new String[4];
        col[0]="Admin";
        col[1]="Operation";
        col[2]="Performing Date";
        col[3]="Manipulated Id";
        populateOnJTable(query,col);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String query="select * from hr.archivedprisoners";
        String col[]=new String[13];
        col[0]="ID";
        col[1]="Name";
        col[2]="DOB";
        col[3]="Height";
        col[4]="Crime";
        col[5]="Punishment";
        col[6]="Visiting Time";
        col[7]="Thana";
        col[8]="District";
        col[9]="Division";
        col[10]="Country";
        col[11]="Insertion Date";
        col[12]="Release Date";
                
        populateOnJTable(query,col);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String query="select * from hr.cell where cellno<>0 and cellno in(select cell from hr.needrepair)";
        String col[]=new String[7];
        col[0]="Cell No";
        col[1]="Row No";
        col[2]="Column";
        col[3]="Floor";
        col[4]="Building No";
        col[5]="Capacity";
        col[6]="Prisoners";
        
        populateOnJTable(query,col);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            
            int row=jTable1.getSelectedRow();
            Object i=tableModel.getValueAt(row, 0);
            String cno=i.toString();
            String tab=(String) jTable1.getColumnModel().getColumn(0).getHeaderValue();
            System.out.println(tab);
            if("Cell No".equals(tab)){
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to make this cell available again?", "Confirmation", dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION) { 
                    String query="delete from hr.needrepair where cell="+cno;
                    dbc.insertUpdate(query);
                    JOptionPane.showMessageDialog(rootPane, "The cell has become available again.");
                    query="select * from hr.cell where cellno<>0 and cellno in(select cell from hr.needrepair)";
                    String col[]=new String[7];
                    col[0]="Cell No";
                    col[1]="Row No";
                    col[2]="Column";
                    col[3]="Floor";
                    col[4]="Building No";
                    col[5]="Capacity";
                    col[6]="Prisoners";
        
                    populateOnJTable(query,col);
                }
            }
            else{
                System.out.println("NOOOOOOOOOOOOOOO");
            }
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
